#!/bin/sh

set -ex

export TEST_QUEUE_WORKERS=2 TEST_QUEUE_VERBOSE=1

if [ -f "Gemfile-$SUITE" ]; then
  export BUNDLE_GEMFILE="Gemfile-$SUITE"
else
  export BUNDLE_GEMFILE=Gemfile
fi

bundle install

if [ ! -f "test/$SUITE.bats" ]; then
  echo >&2 "Unknown SUITE $SUITE"
  exit 1
fi

vendor/bats/bin/bats test/$SUITE.bats
