#!/bin/sh

set -ex

if [ "$SUITE" = "ruby" ]; then
  exec script/spec
fi

export TEST_QUEUE_WORKERS=2 TEST_QUEUE_VERBOSE=1

if [ -f "Gemfile-$SUITE" ]; then
  export BUNDLE_GEMFILE="Gemfile-$SUITE"
else
  export BUNDLE_GEMFILE=Gemfile
fi

bundle install

vendor/bats/bin/bats test
