#!/bin/sh

set -ex

if bundle exec minitest-queue ./test/samples/*_minitest4.rb; then
  echo >&2 "minitest-queue should have failed but didn't"
  exit 1
fi

bundle exec minitest-queue ./test/samples/*_minispec.rb
