#!/bin/sh

set -ex

export TEST_QUEUE_WORKERS=2 TEST_QUEUE_VERBOSE=1

export BUNDLE_GEMFILE=Gemfile-testunit
bundle install

if bundle exec testunit-queue ./test/*_testunit.rb; then
  echo >&2 "testunit-queue should have failed but didn't"
  exit 1
fi
