#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'test_queue'
require 'test_queue/runner/minitest'

TestQueue::Runner::Minitest.new.execute
